function t228__init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlock=rec.querySelector('.t228');var mobileMenu=rec.querySelector('.t228__mobile');var menuSubLinkItems=rec.querySelectorAll('.t-menusub__link-item');var rightBtn=rec.querySelector('.t228__right_buttons_but .t-btn');var mobileMenuPosition=mobileMenu?mobileMenu.style.position||window.getComputedStyle(mobileMenu).position:'';var mobileMenuDisplay=mobileMenu?mobileMenu.style.display||window.getComputedStyle(mobileMenu).display:'';var isFixedMobileMenu=mobileMenuPosition==='fixed'&&mobileMenuDisplay==='block';var overflowEvent=document.createEvent('Event');var noOverflowEvent=document.createEvent('Event');overflowEvent.initEvent('overflow',!0,!0);noOverflowEvent.initEvent('nooverflow',!0,!0);if(menuBlock){menuBlock.addEventListener('overflow',function(){t228_checkOverflow(recid)});$(menuBlock).on('overflow',function(){t228_checkOverflow(recid)});menuBlock.addEventListener('nooverflow',function(){t228_checkNoOverflow(recid)});$(menuBlock).on('nooverflow',function(){t228_checkNoOverflow(recid)})}
rec.addEventListener('click',function(e){var targetLink=e.target.closest('.t-menusub__target-link');if(targetLink&&window.isMobile){if(targetLink.classList.contains('t-menusub__target-link_active')){if(menuBlock)menuBlock.dispatchEvent(overflowEvent)}else{if(menuBlock)menuBlock.dispatchEvent(noOverflowEvent)}}
var currentLink=e.target.closest('.t-menu__link-item:not(.tooltipstered):not(.t-menusub__target-link):not(.t794__tm-link):not(.t966__tm-link):not(.t978__tm-link):not(.t978__menu-link)');if(currentLink&&mobileMenu&&isFixedMobileMenu)mobileMenu.click()});Array.prototype.forEach.call(menuSubLinkItems,function(linkItem){linkItem.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})});if(rightBtn){rightBtn.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})}
if(menuBlock){menuBlock.addEventListener('showME601a',function(){var menuLinks=rec.querySelectorAll('.t966__menu-link');Array.prototype.forEach.call(menuLinks,function(menuLink){menuLink.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})})})}}
function t228_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t228__list_item a[href=\''+url+'\'], '+'.t228__list_item a[href=\''+url+'/\'], '+'.t228__list_item a[href=\''+pathname+'\'], '+'.t228__list_item a[href=\'/'+pathname+'\'], '+'.t228__list_item a[href=\''+pathname+'/\'], '+'.t228__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t228_checkAnchorLinks(recid){if(window.innerWidth>=980){var rec=document.getElementById('rec'+recid);var navLinks=rec?rec.querySelectorAll('.t228__list_item a[href*=\'#\']'):[];navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){setTimeout(function(){t228_catchScroll(navLinks)},500)}}}
function t228_checkOverflow(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t228'):null;if(!menu)return;var mobileContainer=document.querySelector('.t228__mobile_container');var mobileContainerHeight=t228_getFullHeight(mobileContainer);var windowHeight=document.documentElement.clientHeight;var menuPosition=menu.style.position||window.getComputedStyle(menu).position;if(menuPosition==='fixed'){menu.classList.add('t228__overflow');menu.style.setProperty('height',(windowHeight-mobileContainerHeight)+'px','important')}}
function t228_checkNoOverflow(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var menu=rec.querySelector('.t228');var menuPosition=menu?menu.style.position||window.getComputedStyle(menu).position:'';if(menuPosition==='fixed'){if(menu)menu.classList.remove('t228__overflow');if(menu)menu.style.height='auto'}}
function t228_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;navLinks=navLinks.reverse();navLinks.forEach(function(link){var currentSection=t228_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});sections.sort(function(a,b){return b.getBoundingClientRect().top-a.getBoundingClientRect().top});t228_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);navLinks.forEach(function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t228_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t228_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t228_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t228_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t228_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getBoundingClientRect().top+window.pageYOffset;var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t228_setWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuCenterSideList=rec.querySelectorAll('.t228__centerside');Array.prototype.forEach.call(menuCenterSideList,function(menuCenterSide){menuCenterSide.classList.remove('t228__centerside_hidden')});if(window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var maxWidth;var centerWidth=0;var paddingWidth=40;var leftSide=menu.querySelector('.t228__leftside');var rightSide=menu.querySelector('.t228__rightside');var menuList=menu.querySelector('.t228__list');var mainContainer=menu.querySelector('.t228__maincontainer');var leftContainer=menu.querySelector('.t228__leftcontainer');var rightContainer=menu.querySelector('.t228__rightcontainer');var centerContainer=menu.querySelector('.t228__centercontainer');var centerContainerLi=centerContainer?centerContainer.querySelectorAll('li'):[];var leftContainerWidth=t228_getFullWidth(leftContainer);var rightContainerWidth=t228_getFullWidth(rightContainer);var mainContainerWidth=mainContainer?mainContainer.offsetWidth:0;var dataAlign=menu.getAttribute('data-menu-items-align');var isDataAlignCenter=dataAlign==='center'||dataAlign===null;maxWidth=leftContainerWidth>=rightContainerWidth?leftContainerWidth:rightContainerWidth;maxWidth=Math.ceil(maxWidth);Array.prototype.forEach.call(centerContainerLi,function(li){centerWidth+=t228_getFullWidth(li)});if(mainContainerWidth-(maxWidth*2+paddingWidth*2)>centerWidth+20){if(isDataAlignCenter){if(leftSide)leftSide.style.minWidth=maxWidth+'px';if(rightSide)rightSide.style.minWidth=maxWidth+'px';if(menuList)menuList.classList.remove('t228__list_hidden')}}else{if(leftSide)leftSide.style.minWidth=maxWidth+'';if(rightSide)rightSide.style.minWidth=maxWidth+''}})}
function t228_getFullWidth(el){if(!el)return 0;var marginLeft=el.style.marginLeft||window.getComputedStyle(el).marginLeft;var marginRight=el.style.marginRight||window.getComputedStyle(el).marginRight;marginLeft=parseInt(marginLeft,10)||0;marginRight=parseInt(marginRight,10)||0;return el.offsetWidth+marginLeft+marginRight}
function t228_getFullHeight(el){if(!el)return 0;var marginTop=el.style.marginTop||window.getComputedStyle(el).marginTop;var marginBottom=el.style.marginBottom||window.getComputedStyle(el).marginBottom;marginTop=parseInt(marginTop,10)||0;marginBottom=parseInt(marginBottom,10)||0;return el.offsetHeight+marginTop+marginBottom}
function t228_setBg(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t228_appearMenu(recid){if(window.innerWidth<=980)return;var rec=document.getElementById('rec'+recid);if(!rec)return!1;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t228_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t228_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t228_changebgopacitymenu(recid){if(window.innerWidth<=980)return;var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t228_createMobileMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t228');var burger=rec.querySelector('.t228__mobile');if(burger){burger.addEventListener('click',function(){if(burger.classList.contains('t228_opened')){t228_fadeOut(menu,300);burger.classList.remove('t228_opened')}else{t228_fadeIn(menu,300,function(){if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''});burger.classList.add('t228_opened')}})}
window.addEventListener('resize',t_throttle(function(){if(window.innerWidth>980){if(menu.style.opacity)menu.style.opacity='';if(menu.style.display==='none')menu.style.display=''}else if(menu.style.transform)menu.style.transform=''}))}
function t228_fadeOut(element,duration,callback){if(!element)return!1;var opacity=1;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){element.style.opacity='0';element.style.display='none';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t228_fadeIn(element,duration,callback){if(!element)return!1;if((getComputedStyle(element).opacity==='1'||getComputedStyle(element).opacity==='')&&getComputedStyle(element).display!=='none')return!1;var opacity=0;duration=parseInt(duration,10);var speed=duration>0?duration/10:40;element.style.opacity=opacity;element.style.display='block';var timer=setInterval(function(){element.style.opacity=opacity;opacity+=0.1;if(opacity>=1){element.style.opacity='1';if(typeof callback==='function'){callback()}
clearInterval(timer)}},speed)}
function t228_slideUpElement(menu,menuHeight,position){var diff=position==='toTop'?0:menuHeight;var diffOpacity=position==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=position==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=position==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(position==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(position==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t270_scroll(hash,offset,speed){if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var root=$('html, body');var target="";if(speed===undefined){speed=400}
try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
var isHistoryChangeAllowed=window.location.hash!==hash;var complete=function(){if(!isHistoryChangeAllowed){return}
if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
var dontChangeHistory=Boolean($('.t270').attr('data-history-disabled'));if(dontChangeHistory){complete=function(){}}
root.animate({scrollTop:target.offset().top-offset},speed,complete);return!0}
function t367_createCookie(cookieName,cookieValue,cookieTime){var expires='';if(cookieTime){var date=new Date();date.setTime(date.getTime()+cookieTime*24*60*60*1000);expires='; expires='+date.toGMTString()}
document.cookie=cookieName+'='+cookieValue+expires+'; path=/'}
function t367_readCookie(cookieName){cookieName=cookieName+'=';var allCookies=document.cookie.split(';');for(var i=0;i<allCookies.length;i++){var cookie=allCookies[i];while(cookie.charAt(0)===' '){cookie=cookie.substring(1,cookie.length)}
if(cookie.indexOf(cookieName)===0){return cookie.substring(cookieName.length,cookie.length)}}
return null}
function t367_autoInit(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');var windowWidth=window.innerWidth;if(typeof screenMin==='string'){if(windowWidth<parseInt(screenMin,10)){return!0}}
if(typeof screenMax==='string'){if(windowWidth>parseInt(screenMax,10)){return!0}}
var openerLink=rec.querySelector('.t367__opener');var linkhook=openerLink.getAttribute('href');if(!linkhook)return;var cookieName=openerLink.getAttribute('data-cookie-name');var cookieTime=openerLink.getAttribute('data-cookie-time');var cookieValue='t367cookie';var cookie=t367_readCookie(cookieName);var timeout=parseInt(openerLink.getAttribute('data-trigger-time'),10)*1000;var wrapperBlock=rec.querySelector('.t367');if(!wrapperBlock)return;if(cookie)wrapperBlock.innerHTML='';else if(openerLink){setTimeout(function(){var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);openerLink.dispatchEvent(event);wrapperBlock.innerHTML='';t367_createCookie(cookieName,cookieValue,cookieTime)},timeout)}}
function t577_equalHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t577');if(!container)return;container.style.visibility='visible';var rows=rec.querySelectorAll('.t577__row');var textWrappers=rec.querySelectorAll('.t577__textwrapper');var descriptions=rec.querySelectorAll('.t577__descr');for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height='auto'}
for(var i=0;i<descriptions.length;i++){descriptions[i].style.height='auto'}
for(var i=0;i<rows.length;i++){var row=rows[i];var descrs=row.querySelectorAll('.t577__descr');var maxHeight=0;for(var j=0;j<descrs.length;j++){var descr=descrs[j];var descrStyle=getComputedStyle(descr,null);var descrPaddingTop=parseInt(descrStyle.paddingTop)||0;var descrPaddingBottom=parseInt(descrStyle.paddingBottom)||0;var descrHeight=descr.clientHeight-(descrPaddingTop+descrPaddingBottom);if(descrHeight>maxHeight)maxHeight=descrHeight}
if(window.innerWidth>=960){for(var j=0;j<descrs.length;j++){descrs[j].style.height=maxHeight+'px'}}else{for(var j=0;j<descrs.length;j++){descrs[j].style.height='auto'}}
var textWraps=row.querySelectorAll('.t577__textwrapper');maxHeight=0;for(var j=0;j<textWraps.length;j++){var textWrap=textWraps[j];var textWrapStyle=getComputedStyle(textWrap,null);var textWrapPaddingTop=parseInt(textWrapStyle.paddingTop)||0;var textWrapPaddingBottom=parseInt(textWrapStyle.paddingBottom)||0;var textWrapHeight=textWrap.clientHeight-(textWrapPaddingTop+textWrapPaddingBottom);if(textWrapHeight>maxHeight)maxHeight=textWrapHeight}
if(window.innerWidth>=960){for(var j=0;j<textWraps.length;j++){textWraps[j].style.height=maxHeight+'px'}}else{for(var j=0;j<textWraps.length;j++){textWraps[j].style.height='auto'}}}}
function t651_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t651');if(!container)return;if(window.isMobile&&!window.isTablet){var phone=rec.querySelector('.t651__phone');if(!phone)return;var phoneText=phone.textContent.replace(/\s+/g,'');var button=rec.querySelector('.t651__btn');var buttonWrapper=rec.querySelector('.t651__btn_wrapper');var buttonText=rec.querySelector('.t651__btn-text');button.addEventListener('click',function(){window.location.href='tel:'+phoneText;if(buttonWrapper)buttonWrapper.classList.remove('t651__btn_animate');if(buttonText)buttonText.style.display='none'});return}
rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var popup=rec.querySelector('.t651__popup');var analitics=popup.getAttribute('data-track-popup');var hook='TildaCallBackWidget'+recId;var button=rec.querySelector('.t651__btn');button.addEventListener('click',function(event){if(button.classList.contains('t651__btn_active')){t651_closePopup();return}
button.classList.add('t651__btn_active');t651_showPopup(recId);event.preventDefault();if(analitics)Tilda.sendEventToStatistics(analitics,hook)})}
function t651_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popup=rec.querySelector('.t651__popup');if(!popup)return;var buttonWrapper=rec.querySelector('.t651__btn_wrapper');var buttonText=rec.querySelector('.t651__btn-text');if(buttonWrapper)buttonWrapper.classList.remove('t651__btn_animate');if(buttonText)buttonText.style.display='none';popup.style.display='block';setTimeout(function(){popup.classList.add('t651__popup_show')},50);document.addEventListener('keydown',t651_escClosePopup)}
function t651_escClosePopup(event){if(event.key==='Escape')t651_closePopup()}
function t651_closePopup(){var buttons=document.querySelectorAll('.t651__btn');var popups=document.querySelectorAll('.t651__popup');for(var i=0;i<buttons.length;i++){buttons[i].classList.remove('t651__btn_active')}
for(var i=0;i<popups.length;i++){popups[i].classList.remove('t651__popup_show')}
setTimeout(function(){var popupHide=document.querySelectorAll('.t651__popup:not(.t651__popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t651_escClosePopup)}
function t678_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t678__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t678__fadeOut(tildaLabel,50)}},300)}else{t678__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t678__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t678__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t678__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t678__easeInOutCubic(currentTime,change){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t678__animateScroll(){currentTime+=increment;window.scrollTo(0,t678__easeInOutCubic(currentTime,change));if(currentTime<duration){setTimeout(t678__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t678__animateScroll()}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t702_resizePopup(recId);t702__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}})}}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup()});popupCloseBtn.addEventListener('click',t702_closePopup);if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup();if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var range=rec.querySelector('.t-range');var documentBody=document.body;popup.style.display='block';if(range)t702__triggerEvent(range,'popupOpened');setTimeout(function(){popupContainer.classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
document.addEventListener('keydown',t702_escClosePopup);t702__lazyLoad()}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup()}
function t702_closePopup(){var popupAll=document.querySelectorAll('.t-popup');document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t702__body_popupshowed');for(var i=0;i<popupAll.length;i++){popupAll[i].classList.remove('t-popup_show')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',t702_escClosePopup)}
function t702_resizePopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var popupContainer=rec.querySelector('.t-popup__container');if(!popupContainer)return;var popupStyle=getComputedStyle(popupContainer,null);var popupPaddingTop=parseInt(popupStyle.paddingTop)||0;var popupPaddingBottom=parseInt(popupStyle.paddingBottom)||0;var popupHeight=popupContainer.clientHeight-(popupPaddingTop+popupPaddingBottom);if(popupHeight>(window.innerHeight-120)){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsWrapperStyle=getComputedStyle(inputsWrapper,null);var inputsWrapperPaddingTop=parseInt(inputsWrapperStyle.paddingTop)||0;var inputsWrapperPaddingBottom=parseInt(inputsWrapperStyle.paddingBottom)||0;var inputsWrapperHeight=inputsWrapper.clientHeight-(inputsWrapperPaddingTop+inputsWrapperPaddingBottom);var inputsOffset=inputsWrapper.getBoundingClientRect().top+window.pageYOffset;var inputsBottom=inputsWrapperHeight+inputsOffset;var successBox=form.querySelector('.t-form__successbox');var successBoxOffset=successBox.getBoundingClientRect().top+window.pageYOffset;var target=0;var windowHeight=window.innerHeight;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(window.innerWidth>960){target=successBoxOffset-200}else{target=successBoxOffset-100}
var tildaLabel=document.querySelector('.t-tildalabel');if(successBoxOffset>window.scrollY||(documentHeight-inputsBottom)<(windowHeight-100)){inputsWrapper.classList.add('t702__inputsbox_hidden');setTimeout(function(){if(windowHeight>documentHeight&&tildaLabel){t702__fadeOut(tildaLabel)}},300)}else{t702__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t702__inputsbox_hidden')},400)}
var successUrl=$(form).data('success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}}
function t702__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},50)}
function t702__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t702__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t702__animateScroll(){currentTime+=increment;window.scrollTo(0,t702__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t702__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t702__animateScroll()}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t862_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t862');if(!container)return;var quizWrapper=rec.querySelector('.t862__quiz-wrapper');var form=rec.querySelector('.t-form');if(!form)return;var quizQuestions=rec.querySelectorAll('.t-input-group');var prevBtn=rec.querySelector('.t862__btn_prev');var nextBtn=rec.querySelector('.t862__btn_next');var resultBtn=rec.querySelector('.t862__btn_result');var errorBoxMiddle=rec.querySelector('.t-form__errorbox-middle');var captureFormHTML='<div class="t862__capture-form"></div>';var quizQuestionNumber=0;if(errorBoxMiddle){var errorBoxMiddleWrapper=errorBoxMiddle.querySelector('.t-form__errorbox-wrapper')}
errorBoxMiddle.insertAdjacentHTML('beforebegin',captureFormHTML);form.classList.remove('js-form-proccess');quizQuestions[quizQuestionNumber].style.display='block';quizQuestions[quizQuestionNumber].classList.add('t-input-group-step_active');rec.setAttribute('data-animationappear','off');rec.style.opacity=1;t862_workWithAnswerCode(rec);for(var i=0;i<quizQuestions.length;i++){quizQuestions[i].setAttribute('data-question-number',i)}
t862_wrapCaptureForm(rec);var captureForm=rec.querySelector('.t862__capture-form');var resultTitle=rec.querySelector('.t862__result-title');var resultText=resultTitle?resultTitle.textContent:'';t862_showCounter(rec,quizQuestionNumber);t862_disabledPrevBtn(rec,quizQuestionNumber);t862_checkLength(rec);t862_openToHook(rec,quizQuestions,captureForm);prevBtn.addEventListener('click',function(event){if(quizQuestionNumber>0){quizQuestionNumber--}
t862_setProgress(rec,-1);t862__checkMode();t862_awayFromResultScreen(rec);t862_showCounter(rec,quizQuestionNumber);t862_hideError(rec,quizQuestionNumber);t862_disabledPrevBtn(rec,quizQuestionNumber);t862_switchQuestion(rec,quizQuestionNumber);t862_resizePopup(rec);event.preventDefault()});nextBtn.addEventListener('click',function(event){var showErrors=t862_showError(rec,quizWrapper,quizQuestionNumber);if(showErrors&&errorBoxMiddleWrapper){errorBoxMiddleWrapper.style.display='none'}
if(!showErrors){quizQuestionNumber++;prevBtn.removeAttribute('disabled');t862_setProgress(rec,1);t862_showCounter(rec,quizQuestionNumber);t862_switchQuestion(rec,quizQuestionNumber);t862_resizePopup(rec)}
t862__checkMode();event.preventDefault()});for(var i=0;i<quizQuestions.length;i++){var quizQuestion=quizQuestions[i];quizQuestion.addEventListener('keypress',function(event){var activeStep=form.querySelector('.t-input-group-step_active');if(event.code==='Enter'&&!form.classList.contains('js-form-proccess')&&!activeStep.classList.contains('t-input-group_ta')){var showErrors=t862_showError(rec,quizWrapper,quizQuestionNumber);var arrQuestion=t862_createQuestionArr(rec);if(showErrors&&errorBoxMiddleWrapper){errorBoxMiddleWrapper.style.display='none'}
prevBtn.removeAttribute('disabled');if(!showErrors){quizQuestionNumber++;t862_setProgress(rec,1);t862_showCounter(rec,quizQuestionNumber);if(quizQuestionNumber<arrQuestion.length){t862_switchQuestion(rec,quizQuestionNumber)}else{t862_switchResultScreen(rec);form.classList.add('js-form-proccess')}
t862_disabledPrevBtn(rec,quizQuestionNumber)}
t862__checkMode();event.preventDefault()}})}
resultBtn.addEventListener('click',function(event){var showErrors=t862_showError(rec,quizWrapper,quizQuestionNumber);if(showErrors&&errorBoxMiddleWrapper){errorBoxMiddleWrapper.style.display='none'}
if(!showErrors){quizQuestionNumber++;t862_setProgress(rec,1);form.classList.add('js-form-proccess');t862_disabledPrevBtn(rec,quizQuestionNumber);if(!captureForm.innerHTML&&!resultText){t862_showCounter(rec,quizQuestionNumber);t862_switchQuestion(rec,quizQuestionNumber)}else{t862_switchResultScreen(rec)}}
event.preventDefault()})}
function t862_workWithAnswerCode(rec){var riInputs=rec.querySelectorAll('.t-input-group_ri input');var rdInputs=rec.querySelectorAll('.t-input-group_rd input');var sbOptions=rec.querySelectorAll('.t-input-group_sb option');for(var i=0;i<riInputs.length;i++){var input=riInputs[i];if(input.value.indexOf('value::')!==-1){t862_setAnswerCode(input);var text=input.parentNode.querySelector('.t-img-select__text');if(text){text.textContent=text.textContent.split('value::')[0].trim()}}}
for(var i=0;i<rdInputs.length;i++){var input=rdInputs[i];if(input.value.indexOf('value::')!==-1){t862_setAnswerCode(input);var label=input.parentNode;if(label){label.innerHTML=label.innerHTML.split('value::')[0].trim()}}}
for(var i=0;i<sbOptions.length;i++){var option=sbOptions[i];if(option.value.indexOf('value::')!==-1){t862_setAnswerCode(option);option.textContent=option.textContent.split('value::')[0].trim()}}}
function t862_setAnswerCode(element){element.value=element.value.split('value::')[1].trim()}
function t862_wrapCaptureForm(rec){var captureForm=rec.querySelector('.t862__capture-form');var quizQuestions=rec.querySelectorAll('.t-input-group');var quizFormWrapper=rec.querySelector('.t862__quiz-form-wrapper');for(var i=0;i<quizQuestions.length;i++){var quizQuestion=quizQuestions[i];var isEmail=quizQuestion.classList.contains('t-input-group_em');var isName=quizQuestion.classList.contains('t-input-group_nm');var isPhone=quizQuestion.classList.contains('t-input-group_ph');var isCheckbox=quizQuestion.classList.contains('t-input-group_cb');var quizQuestionNumber=quizQuestion.getAttribute('data-question-number');var maxCountOfCaptureFields=4;if(quizQuestionNumber>=quizQuestions.length-maxCountOfCaptureFields){var isCaptureGroup=!0;if(quizFormWrapper.classList.contains('t862__quiz-form-wrapper_newcapturecondition')){var inputsGroup=t862__nextAll(quizQuestion,'.t-input-group');for(var j=0;j<inputsGroup.length;j++){var inputGroup=inputsGroup[j];isCaptureGroup=inputGroup.classList.contains('t-input-group_cb')||inputGroup.classList.contains('t-input-group_em')||inputGroup.classList.contains('t-input-group_nm')||inputGroup.classList.contains('t-input-group_ph')}}
if(isCaptureGroup){if(isEmail||isName||isPhone||isCheckbox){quizQuestion.classList.add('t862__t-input-group_capture');captureForm.appendChild(quizQuestion)}}}}}
function t862_showCounter(rec,quizQuestionNumber){var counter=rec.querySelector('.t862__quiz-description-counter');if(!counter)return;var arrQuestion=t862_createQuestionArr(rec);counter.innerHTML=quizQuestionNumber+1+'/'+arrQuestion.length}
function t862_createQuestionArr(rec){var quizQuestions=rec.querySelectorAll('.t-input-group');var arrQuestion=[];for(var i=0;i<quizQuestions.length;i++){var quizQuestion=quizQuestions[i];if(!quizQuestion.classList.contains('t862__t-input-group_capture')){arrQuestion.push(quizQuestion)}}
return arrQuestion}
function t862_disabledPrevBtn(rec,quizQuestionNumber){var prevBtn=rec.querySelector('.t862__btn_prev');if(quizQuestionNumber===0){prevBtn.setAttribute('disabled','')}else{prevBtn.removeAttribute('disabled')}}
function t862_checkLength(rec){var nextBtn=rec.querySelector('.t862__btn_next');var resultBtn=rec.querySelector('.t862__btn_result');var arrQuestion=t862_createQuestionArr(rec);var submitBtnWrapper=rec.querySelector('.t-form__submit');var captureForm=rec.querySelector('.t862__capture-form');var resultTitle=rec.querySelector('.t862__result-title');var resultText=resultTitle?resultTitle.textContent:'';if(!captureForm.innerHTML&&!resultText&&arrQuestion.length<2){nextBtn.style.display='none';resultBtn.style.display='none';submitBtnWrapper.style.display='block'}else if(arrQuestion.length<2){nextBtn.style.display='none';resultBtn.style.display='block'}}
function t862_openToHook(rec,quizQuestions,captureForm){var popup=rec.querySelector('.t-popup');var popupCloseBtn=rec.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var hook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var escepeEvent=t862__escClosePopup.bind(popup,rec);if(hook){document.addEventListener('click',function(event){if(event.target.closest('a[href="'+hook+'"]')){event.preventDefault();t862_showPopup(rec,quizQuestions,captureForm,escepeEvent);setTimeout(function(){t862_resizePopup(rec)},50);t862__lazyLoad();if(analitics){var virtTitle=hook;if(virtTitle.substring(0,7)=='#popup:'){virtTitle=virtTitle.substring(7)}
Tilda.sendEventToStatistics(analitics,virtTitle)}}})}
popup.addEventListener('click',function(event){if(event.target===this)t862_closePopup(rec,escepeEvent)});popupCloseBtn.addEventListener('click',function(){t862_closePopup(rec,escepeEvent)});for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||(url.substring(0,7)!='#price:'&&url.substring(0,7)!='#order:')){t862_closePopup(rec,escepeEvent);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){document.body.classList.add('t-body_popupshowed')},300)}}})}}
function t862_setProgress(rec,index){var progressBar=rec.querySelector('.t862__progressbar');var progress=rec.querySelector('.t862__progress');var questionCount=t862_createQuestionArr(rec).length;var captureForm=rec.querySelector('.t862__capture-form');var resultTitle=rec.querySelector('.t862__result-title');var resultText=resultTitle?resultTitle.textContent:'';var progressbarWidth=0;var progressBarStyle=getComputedStyle(progressBar,null);var progressBarPaddingLeft=parseInt(progressBarStyle.paddingLeft)||0;var progressBarPaddingRight=parseInt(progressBarStyle.paddingRight)||0;progressbarWidth=progressBar.clientWidth-(progressBarPaddingLeft+progressBarPaddingRight);if(!captureForm.innerHTML&&!resultText&&questionCount>0){questionCount--}
var progressWidth=progress.getAttribute('data-progress-bar');if(!progressWidth){progressWidth=0;progress.setAttribute('data-progress-bar','0')}
var progressStep=progressbarWidth/questionCount;var percentProgress=(parseFloat(progressWidth)+(index*progressStep))/progressbarWidth*100;if(isNaN(percentProgress)||percentProgress===-Infinity){percentProgress=0;progress.setAttribute('data-progress-bar',percentProgress)}else if(percentProgress===Infinity){percentProgress=progressbarWidth;progress.setAttribute('data-progress-bar',percentProgress)}else{progress.setAttribute('data-progress-bar',progressbarWidth/100*percentProgress)}
if(percentProgress>100){percentProgress=100}else if(percentProgress<0){percentProgress=0}
if(progress)progress.style.width=percentProgress+'%'}
function t862__checkMode(){if(document.getElementById('allrecords').getAttribute('data-tilda-mode')){t862__lazyLoad()}}
function t862__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t862_awayFromResultScreen(rec){var captureForm=rec.querySelector('.t862__capture-form');var quizDescription=rec.querySelector('.t862__quiz-description');var resultTitle=rec.querySelector('.t862__result-title');var submitBtnWrapper=rec.querySelector('.t-form__submit');captureForm.style.display='none';if(resultTitle)resultTitle.style.display='none';if(submitBtnWrapper)submitBtnWrapper.style.display='none';if(quizDescription)quizDescription.style.display='block'}
function t862_hideError(rec,quizQuestionNumber){var arrQuestion=t862_createQuestionArr(rec);var activeQuestion=arrQuestion[quizQuestionNumber];if(!activeQuestion)return;activeQuestion.classList.remove('js-error-control-box');activeQuestion.querySelector('.t-input-error').innerHTML=''}
function t862_switchQuestion(rec,quizQuestionNumber){var nextBtn=rec.querySelector('.t862__btn_next');var resultBtn=rec.querySelector('.t862__btn_result');var arrQuestion=t862_createQuestionArr(rec);var submitBtnWrapper=rec.querySelector('.t-form__submit');var captureForm=rec.querySelector('.t862__capture-form');var resultTitle=rec.querySelector('.t862__result-title');var resultText=resultTitle?resultTitle.textContent:'';for(var i=0;i<arrQuestion.length;i++){var question=arrQuestion[i];question.style.display='none';question.classList.remove('t-input-group-step_active')}
var activeQuestion=arrQuestion[quizQuestionNumber];var range=activeQuestion.querySelector('.t-range');activeQuestion.style.display='block';activeQuestion.classList.add('t-input-group-step_active');if(range)t862__triggerEvent(range,'displayChanged');var captureFormHTML=captureForm.innerHTML;if(!captureFormHTML&&!resultText&&quizQuestionNumber===arrQuestion.length-2){nextBtn.style.display='none';resultBtn.style.display='block';submitBtnWrapper.style.display='none'}else if(!captureFormHTML&&!resultText&&quizQuestionNumber===arrQuestion.length-1){nextBtn.style.display='none';resultBtn.style.display='none';submitBtnWrapper.style.display='block'}else if(quizQuestionNumber===arrQuestion.length-1){nextBtn.style.display='none';resultBtn.style.display='block';submitBtnWrapper.style.display='none'}else{nextBtn.style.display='block';resultBtn.style.display='none';submitBtnWrapper.style.display='none'}}
function t862_showError(rec,quizWrapper,quizQuestionNumber){if(quizWrapper.classList.contains('t862__quiz-published')){return t862_setError(rec,quizQuestionNumber)}}
function t862_setError(rec,quizQuestionNumber){var arrQuestion=t862_createQuestionArr(rec);var activeQuestion=arrQuestion[quizQuestionNumber];var showErrors;if(typeof window.tildaForm!=='object')return showErrors;var arrErrors=window.tildaForm.validate(activeQuestion);var errorsTypeObj=arrErrors[0];activeQuestion.classList.add('js-error-control-box');if(errorsTypeObj){var errorType=errorsTypeObj.type[0];var error=rec.querySelector('.t-form .t-form__errorbox-middle .js-rule-error-'+errorType);var strError='';if(error)strError=error.textContent;if(!strError){t_onFuncLoad('t_form_dict',function(){strError=t_form_dict(errorType)})}
if(errorType==='emptyfill'){showErrors=!1}else{showErrors=window.tildaForm.showErrors(activeQuestion,arrErrors)}
var inputError=activeQuestion.querySelector('.t-input-error');if(inputError)inputError.innerHTML=strError}
return showErrors}
function t862_switchResultScreen(rec){var resultBtn=rec.querySelector('.t862__btn_result');var submitBtnWrapper=rec.querySelector('.t-form__submit');var captureForm=rec.querySelector('.t862__capture-form');var resultTitle=rec.querySelector('.t862__result-title');if(captureForm.innerHTML||resultTitle.textContent){var quizDescription=rec.querySelector('.t862__quiz-description');var arrQuestion=t862_createQuestionArr(rec);for(var i=0;i<arrQuestion.length;i++){arrQuestion[i].style.display='none'}
captureForm.style.display='block';resultTitle.style.display='block';quizDescription.style.display='none'}
resultBtn.style.display='none';submitBtnWrapper.style.display='block'}
function t862_onSuccess(form){var body=document.body;var html=document.documentElement;var scrollTop=window.pageYOffset;var windowHeight=window.innerHeight;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);if(!(form instanceof Element))form=form[0];var inputsWrapper=form.querySelector('.t-form__inputsbox');var inputsHeight=parseInt(getComputedStyle(inputsWrapper,null).height)||0;var inputsRect=inputsWrapper.getBoundingClientRect();var inputsOffsetTop=inputsRect.top+scrollTop;var inputsBottom=inputsHeight+inputsOffsetTop;var successBox=form.querySelector('.t-form__successbox');var successBoxRect=successBox.getBoundingClientRect();var successBoxOffsetTop=successBoxRect.top+scrollTop;var prevBtn=form.closest('.t862').querySelector('.t862__btn_prev');var target;if(window.innerWidth>960){target=successBoxOffsetTop-200}else{target=successBoxOffsetTop-100}
if(successBoxOffsetTop>scrollTop||documentHeight-inputsBottom<windowHeight-100){inputsWrapper.classList.add('t862__inputsbox_hidden');var tildaLabel=document.querySelector('.t-tildalabel');if(tildaLabel){setTimeout(function(){if(windowHeight>documentHeight){t862__fadeOut(tildaLabel)}},300)}}else{t862__scroll(target);setTimeout(function(){inputsWrapper.classList.add('t862__inputsbox_hidden')},400)}
var successUrl=form.getAttribute('data-success-url');if(successUrl){setTimeout(function(){window.location.href=successUrl},500)}
prevBtn.style.display='none'}
function t862_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t862_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top='';documentBody.removeAttribute('data-popup-scrolltop');window.scrollTo(0,parseInt(bodyScrollTop))}}
function t862_showPopup(rec,quizQuestions,captureForm,escapeEvent){var windowWidth=window.innerWidth;var body=document.body;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var quiz=rec.querySelector('.t862__quiz');var range=rec.querySelector('.t-range');popup.style.display='block';if(range)t862__triggerEvent(range,'popupOpened');t862__lazyLoad();setTimeout(function(){popup.classList.add('t-popup_show');popupContainer.classList.add('t-popup__container-animated');if(windowWidth>640&&quiz.classList.contains('t862__quiz_fixedheight')){t862_setHeight(rec,quizQuestions,captureForm)}
if(windowWidth<=640)t862_setMobileHeight();t862__showJivo('1','1')},50);body.classList.add('t-body_popupshowed');body.classList.add('t862__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){setTimeout(function(){t862_lockScroll()},500)}
document.addEventListener('keydown',escapeEvent)}
function t862__escClosePopup(rec,escapeEvent){if(arguments[1].key==='Escape')t862_closePopup(rec,escapeEvent)}
function t862_setHeight(rec,quizQuestions,captureForm){var quizWrapper=rec.querySelector('.t862__quiz-form-wrapper');var resultTitle=rec.querySelector('.t862__result-title');var resultDescr=rec.querySelector('.t862__quiz-description');var resultTitleHeight=resultTitle?resultTitle.offsetHeight:0;var quizDescriptionHeight=resultDescr?resultDescr.offsetHeight:0;var questions=[];var questionsHeight=[];for(var i=0;i<quizQuestions.length;i++){var quizQuestion=quizQuestions[i];if(!quizQuestion.classList.contains('t862__t-input-group_capture')){questions.push(quizQuestion)}}
for(var i=0;i<questions.length;i++){questionsHeight.push(questions[i].offsetHeight)}
var maxHeightQuestion=Math.max.apply(null,questionsHeight);captureForm.style.display='block';var captureFormHeight=0;var inputsBlock=captureForm.querySelectorAll('.t-input-block');for(var i=0;i<inputsBlock.length;i++){var inputBlock=inputsBlock[i];var inputBlockStyle=getComputedStyle(inputBlock,null);var inputBlockHeight=parseInt(inputBlockStyle.height)||0;var inputBlockMarginBottom=parseInt(inputBlockStyle.marginBottom)||0;captureFormHeight+=(inputBlockHeight+inputBlockMarginBottom)}
captureForm.style.display='none';var height=maxHeightQuestion>captureFormHeight?maxHeightQuestion:captureFormHeight;for(var i=0;i<questions.length;i++){questions[i].style.minHeight=height+'px'}
captureForm.style.minHeight=height+'px';quizWrapper.style.minHeight=height+'px';var headerHeight=resultTitleHeight>quizDescriptionHeight?resultTitleHeight:quizDescriptionHeight;var quizWrapperHeight=quizWrapper.offsetHeight;var btnHeight=rec.querySelector('.t862__btn-wrapper').offsetHeight;rec.querySelector('.t862__wrapper').style.minHeight=(headerHeight+quizWrapperHeight+btnHeight)+'px'}
function t862_setMobileHeight(){t862_calcVH();window.addEventListener('resize',t862_calcVH)}
function t862_calcVH(){var vh=window.innerHeight*0.01;document.documentElement.style.setProperty('--vh',vh+'px')}
function t862_closePopup(rec,escapeEvent){var body=document.body;var popup=rec.querySelector('.t-popup');var popupActive=document.querySelector('.t-popup.t-popup_show');if(popup===popupActive){body.classList.remove('t-body_popupshowed');body.classList.remove('t862__body_popupshowed')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t862_unlockScroll()}
popup.classList.remove('t-popup_show');t862__showJivo('2147483647','2147483648');setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);document.removeEventListener('keydown',escapeEvent)}
function t862_resizePopup(rec){var windowHeight=window.innerHeight-120;var popupContainer=rec.querySelector('.t-popup__container');var popupContainerStyle=getComputedStyle(popupContainer,null);var popupContainerPaddingTop=parseInt(popupContainerStyle.paddingTop)||0;var popupContainerPaddingBottom=parseInt(popupContainerStyle.paddingBottom)||0;var popupContainerHeight=popupContainer.clientHeight-(popupContainerPaddingTop+popupContainerPaddingBottom);if(popupContainerHeight>windowHeight){popupContainer.classList.add('t-popup__container-static')}else{popupContainer.classList.remove('t-popup__container-static')}}
function t862__showJivo(indexMobile,indexDesktop){var jivoBtn=document.querySelectorAll('._show_1e.wrap_mW.__jivoMobileButton');var jivoLabel=document.querySelectorAll('.label_39#jvlabelWrap');for(var i=0;i<jivoBtn.length;i++){jivoBtn[i].style.zIndex=indexMobile}
for(var i=0;i<jivoLabel.length;i++){jivoLabel[i].style.zIndex=indexDesktop}}
function t862_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t862__nextAll(element,selector){var nextElements=[];var nextElement=element;while(nextElement.nextElementSibling){nextElement=nextElement.nextElementSibling;if(nextElement.matches(selector)){nextElements.push(nextElement)}}
return nextElements}
function t862__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t862__fadeOut(element){var elementStyle=getComputedStyle(element,null);if(elementStyle.display==='none'||elementStyle.opacity==='0')return;var opacity=1;var timer=setInterval(function(){element.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);element.style.display='none';element.style.opacity=null}},50)}
function t862__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;var documentBody=document.body;documentBody.setAttribute('data-scrollable','true');function t862__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t862__animateScroll(){currentTime+=increment;window.scrollTo(0,t862__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t862__animateScroll,increment)}else{documentBody.removeAttribute('data-scrollable')}}
t862__animateScroll()}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var button=rec.querySelector('.t890__arrow');var windowOffset='';if(offset){windowOffset=offset}else{windowOffset=window.innerHeight}
rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));button.addEventListener('click',t890__scrollToTop)}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){var duration=700;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=0-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t890__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t890__animateScroll(){currentTime+=increment;window.scrollTo(0,t890__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t890__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t890__animateScroll()}